Add mechanism to stop playing in case of dispose or changing source
ant-media/videojs-webrtc-plugin pull request #18
Opened 2023-03-20 00:07 UTC by mustafaboleken

https://github.com/ant-media/Ant-Media-Server/issues/4851

2023-03-20 09:33 UTC, mekya requested changes

2023-03-20 09:33 UTC, mekya commented on src/plugin.js
> +    window.videojsWebrtcPlayerStreamName = this.source.streamName = source.src.split('/')[4].split('.webrtc')[0];
Using global objects may cause problem if there is more than one player in the same page. Please don't use global objects

2023-03-20 13:53 UTC, hikeeba commented on src/plugin.js
> +    window.videojsWebrtcPlayerStreamName = this.source.streamName = source.src.split('/')[4].split('.webrtc')[0];
We have systems that have multiple players on the same page. It would be great to support that model.

2023-03-20 14:17 UTC, mustafaboleken commented on src/plugin.js
> +    window.videojsWebrtcPlayerStreamName = this.source.streamName = source.src.split('/')[4].split('.webrtc')[0];
Sure, I will refactor to support multiple player in a page.

2023-03-21 20:21 UTC, hikeeba commented on src/plugin.js
> +    window.videojsWebrtcPlayerStreamName = this.source.streamName = source.src.split('/')[4].split('.webrtc')[0];
Here are the changes I made to a local copy to get this to work for us: https://editor.mergely.com/V0lz0NRX/

Feel free to use that as you wish. Basically I added some handling to properly dispose of everything when the handler is called again.

2023-04-03 18:07 UTC, hikeeba reviewed
This looks good to me. Thank you for the updates.

2023-04-05 05:22 UTC, mekya approved these changes
Thank you @hikeeba @mustafaboleken

2023-04-05 05:22 UTC, merged